export const aboutMenuItems = [
  {
    slug: 'overview',
    title: 'বানারীপাড়া',
    icon: 'https://img.icons8.com/?size=100&id=U1cbNtgDXO2m&format=png&color=000000',
    image: '/images/banaripara1.jpg',
    description: 'এক নজরে বানারীপাড়া উপজেলার ঐতিহ্য, পরিসংখ্যান ও পরিচিতি।',
    type: 'overview',
  },
  {
    slug: 'map',
    title: 'বানারীপাড়ার ম্যাপ',
    icon: 'https://img.icons8.com/?size=100&id=vb6KFQas4NTc&format=png&color=000000',
    image: '/images/banariparamap.png',
    description: 'বানারীপাড়া উপজেলার মানচিত্র।',
    type: 'map',
  },
  {
    slug: 'freedom-fighter',
    title: 'মুক্তিযুদ্ধে বানারীপাড়া',
    icon: 'https://img.icons8.com/?size=100&id=2Yy0nV1Bc9Nb&format=png&color=000000',
    image: '/images/freedom.jpg',
    description: '৭১’র মুক্তিযুদ্ধে বানারীপাড়ার সংক্ষিপ্ত ইতিহাস।',
    type: 'freedom',
  },
  {
    slug: 'municipality',
    title: 'পৌরসভা',
    icon: 'https://img.icons8.com/?size=100&id=QRiRloWewAYH&format=png&color=000000',
    image: '/images/organizationalStructure.jpg',
    description: 'এক নজরে বানারীপাড়া পৌরসভা।',
    type: 'municipality',
  },
  {
    slug: 'representatives',
    title: 'জনপ্রতিনিধি',
    icon: 'https://img.icons8.com/?size=100&id=H0QRXByLliQi&format=png&color=000000',
    image: '/images/banariparaProtinidi.png',
    description: 'জনপ্রতিনিধিদের তথ্য এই সেকশনে যুক্ত করা হবে।',
    type: 'simple',
  },
  {
    slug: 'unions',
    title: 'ইউনিয়ন',
    icon: 'https://img.icons8.com/?size=100&id=TQ8KtjwtzKl6&format=png&color=000000',
    image: '/images/banariparamap.png',
    description: 'বানারীপাড়া উপজেলার ৮টি ইউনিয়নের তথ্য।',
    type: 'unions',
  },
  {
    slug: 'government-offices',
    title: 'সরকারী অফিস',
    icon: 'https://img.icons8.com/?size=100&id=46425&format=png&color=000000',
    image: '/images/banaripara1.jpg',
    description: 'সরকারী অফিস সম্পর্কিত তথ্য এই সেকশনে যুক্ত করা হবে।',
    type: 'simple',
  },
  {
    slug: 'education',
    title: 'শিক্ষা প্রতিষ্ঠান',
    icon: 'https://img.icons8.com/?size=100&id=42810&format=png&color=000000',
    image: '/images/schoolCollege.jpeg',
    description: 'বানারীপাড়ার স্কুল, কলেজ, মাদ্রাসা ও অন্যান্য শিক্ষা প্রতিষ্ঠানের তথ্য।',
    type: 'education',
  },
  {
    slug: 'famous-persons',
    title: 'প্রখ্যাত ব্যাক্তিত্ব',
    icon: 'https://img.icons8.com/?size=100&id=xr2bJR33KDz1&format=png&color=000000',
    image: '/images/banariparaMan.png',
    description: 'বানারীপাড়ার গুণীজন ও প্রখ্যাত ব্যক্তিত্বদের পরিচিতি।',
    type: 'persons',
  },
  {
    slug: 'hat-bazar',
    title: 'হাট-বাজার',
    icon: 'https://img.icons8.com/?size=100&id=XrEFnp33pJYw&format=png&color=000000',
    image: '/images/hatbazar.png',
    description: 'বানারীপাড়ার হাট-বাজার তালিকা ও Google Map search link।',
    type: 'markets',
  },
];

export function getAboutItem(slug) {
  return aboutMenuItems.find((item) => item.slug === slug);
}
